# Generated by Django 4.0.4 on 2022-12-18 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30, verbose_name='Banco')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.IntegerField(verbose_name='Número de factura')),
                ('emision_date', models.DateTimeField(verbose_name='Fecha de emisión')),
                ('seller_name', models.CharField(max_length=60, verbose_name='Nombre vendedor')),
                ('seller_last_name', models.CharField(max_length=60, verbose_name='Apellido vendedor')),
                ('observations', models.CharField(blank=True, max_length=120, null=True, verbose_name='Observaciones')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal')),
                ('iva', models.IntegerField(verbose_name='IVA')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('limit_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('iban', models.CharField(blank=True, max_length=60, null=True, verbose_name='IBAN')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Número de contacto')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.bank', verbose_name='Banco')),
            ],
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlative', models.IntegerField(verbose_name='Correlativo')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='Descripción')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('unitary_price', models.IntegerField(verbose_name='Precio unitario')),
                ('discount', models.IntegerField(verbose_name='Descuento')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.bill', verbose_name='Número factura')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=64, verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune_name', models.CharField(max_length=64, verbose_name='Comuna')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.city', verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=20, verbose_name='Unidad de medida')),
                ('symbol', models.CharField(max_length=20, verbose_name='Símbolo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=60, verbose_name='Nombre Proyecto')),
                ('surface', models.IntegerField(verbose_name='Superficie(m2)')),
                ('total_price', models.IntegerField(blank=True, null=True, verbose_name='Presupuesto')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=64, verbose_name='Región')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=60, verbose_name='Nombre')),
                ('last_names', models.CharField(max_length=60, verbose_name='Apellido')),
                ('contact', models.IntegerField(verbose_name='Celular')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, verbose_name='Rut Proveedor')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=60, verbose_name='Apellido')),
                ('address', models.CharField(max_length=60, verbose_name='Dirección')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.city', verbose_name='Ciudad')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.commune', verbose_name='Comuna')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=60, verbose_name='Trabajo')),
                ('payment', models.IntegerField(verbose_name='Costo')),
                ('balance', models.IntegerField(verbose_name='Deuda')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.project', verbose_name='Proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.worker', verbose_name='Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.billdetail', verbose_name='Producto')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.project', verbose_name='Proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, verbose_name='Nombre del producto')),
                ('category', models.CharField(max_length=30, verbose_name='Categoría')),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.measureunit', verbose_name='Unidad de medida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_name', models.CharField(max_length=30, verbose_name='Método de pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_rut', models.CharField(max_length=12, verbose_name='Rut Cliente')),
                ('client_name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('client_last_name', models.CharField(max_length=60, verbose_name='Apellido')),
                ('client_address', models.CharField(max_length=60, verbose_name='Dirección')),
                ('client_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.city', verbose_name='Ciudad')),
                ('client_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.commune', verbose_name='Comuna')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.paymentmethod', verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='bill',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
