# Generated by Django 4.0.4 on 2022-12-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='correlative',
            field=models.IntegerField(unique=True, verbose_name='Correlativo'),
        ),
    ]
