# Generated by Django 4.0.4 on 2022-12-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0006_alter_project_username_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='payment',
        ),
        migrations.AddField(
            model_name='projectworker',
            name='balance',
            field=models.IntegerField(default=int, verbose_name='Deuda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectworker',
            name='payment',
            field=models.IntegerField(default=int, verbose_name='Costo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Presupuesto'),
        ),
    ]
