# Generated by Django 4.0.4 on 2022-12-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0007_remove_worker_balance_remove_worker_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='contact',
            field=models.IntegerField(default=int, max_length=12, verbose_name='Celular'),
            preserve_default=False,
        ),
    ]
