# Generated by Django 4.0.4 on 2022-12-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0008_worker_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=64, verbose_name='Ciudad'),
        ),
    ]
