# Generated by Django 4.0.4 on 2022-12-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0009_alter_city_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='commune_name',
            field=models.CharField(max_length=64, verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(max_length=64, verbose_name='Región'),
        ),
    ]
